name: "Checkout code"
runs-on: ubuntu-latest

runs:
  using: "composite"

  steps:
  - name: Set version number
    run: |
      VERSION=100000
      echo "${VERSION#*release-}" >> version.txt

  - name: Upload version number file
    uses: actions/upload-artifact@v3
    with:
      name: version
      path: version.txt
