name: "Checkout code"
# runs-on: ubuntu-latest
outputs:
  test: # id of output
    description: 'The time we greeted you'
    value: ${{ steps.step1.outputs.test }}
    # output1: ${{ steps.step1.outputs.test }}
    # output2: ${{ steps.step2.outputs.test }}

runs:
  using: "composite"

  steps:
  - run: echo ${{ env.info }}
    shell: bash

  - run:  echo "version_num=1.0.1" >> ${GITHUB_ENV}
    shell: bash

  - run: echo ${{ env.version_num }}
    shell: bash

  - run: echo "1.0.0" >> version.txt
    shell: bash

  - uses: actions/upload-artifact@v3
    with:
      name: version
      path: version.txt

  - id: step1
    run: echo "::set-output name=test::hello"
    shell: bash

  # - id: step2
  #   run: echo "::set-output name=test::world"
  #   shell: bash


