name: "Checkout code"
# runs-on: ubuntu-latest

runs:
  using: "composite"
  outputs:
    output1: ${{ steps.step1.outputs.test }}
    output2: ${{ steps.step2.outputs.test }}

  steps:
  - run:  echo "version_num=1.0.0" >> ${GITHUB_ENV}
    shell: bash

  - run: echo "1.0.0" >> version.txt
    shell: bash

  - uses: actions/upload-artifact@v3
    with:
      name: version
      path: version.txt

  - id: step1
    run: echo "::set-output name=test::hello"
    shell: bash

  - id: step2
    run: echo "::set-output name=test::world"
    shell: bash


