name: Release

on:
  push:
    branches: master

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/actions/checkout-code

    - name: Download version number file
      uses: actions/download-artifact@v3
      with:
        name: version

    - name: Get version number
      run: echo "version=$(cat version.txt)"

