name: Release

on:
  push:
    branches: master

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/actions/checkout-code

    - name: Get version number
      run: echo "version_num=${{ env.version_num }}"

    - name: Download version number file
      uses: actions/download-artifact@v3
      with:
        name: version

    - name: Get version number
      run: echo "version=$(cat version.txt)"

  version_job:
    name: Create version number
    runs-on: ubuntu-latest
    steps:
    - id: version_step
      run: echo "::set-output name=version_number::1.2.3"

  output:
    name: Output
    runs-on: ubuntu-latest
    needs: version_job
    steps:
    - run: echo "${{ needs.version_job.steps.version_step.outputs.version_number }}"

