name: Release

on:
  push:
    branches: master

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/actions/checkout-code

    # - name: Get version number
    #   run: echo "version_num=${{ env.version_num }}"

    # - name: Download version number file
    #   uses: actions/download-artifact@v3
    #   with:
    #     name: version

    # - name: Get version number
    #   run: echo "version=$(cat version.txt)"

  job2:
    runs-on: ubuntu-latest
    needs: checkout-code
    steps:
    - run: echo ${{ needs.checkout-code.outputs.output1 }} ${{ needs.checkout-code.outputs.output2 }}


  # version_job:
  #   name: Create version number
  #   runs-on: ubuntu-latest
  #   steps:
  #   - id: version_step
  #     run: echo "::set-output name=version_number::1.2.3"

  # output:
  #   name: Output
  #   runs-on: ubuntu-latest
  #   needs: version_job
  #   steps:
  #   - run: echo "${{ needs.version_job.steps.version_step.outputs.version_number }}"

  # job1:
  #   runs-on: ubuntu-latest
  #   # Map a step output to a job output outputs: output1:${{steps.step1.outputs.test}}output2:${{steps.step2.outputs.test}}
  #   steps:
  #   - id: step1
  #     run: echo"::set-output name=test::hello"
  #   - id: step2
  #     run: echo"::set-output name=test::world"
  # job2:
  #   runs-on: ubuntu-latest
  #   needs: job1
  #   steps:
  #   - run: echo${{needs.job1.outputs.output1}}${{needs.job1.outputs.output2}}

  # job1:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     output1: ${{ steps.step1.outputs.test }}
  #     output2: ${{ steps.step2.outputs.test }}
  #   steps:
  #   - id: step1
  #     run: echo "::set-output name=test::hello"
  #   - id: step2
  #     run: echo "::set-output name=test::world"
  # job2:
  #   runs-on: ubuntu-latest
  #   needs: job1
  #   steps:
  #   - run: echo ${{ needs.job1.outputs.output1 }} ${{ needs.job1.outputs.output2 }}
